{% set version = "0.1.1" %}

package:
  name: hisseg
  version: {{ version }}

source:
  url: https://github.com/DojakM/histologySegmentationPrediction

build:
  number: 1

requirements:
  host:
    pip
  run:
    pytorch=1.13.1
    pytorch-lightning=1.9.0
    torchaudio=0.13.1
    torchmetrics=0.11.1
    torchvision=0.14.1


test:
  commands:
    - cli_pred.py --help

about:
  home: https://github.com/DojakM/histologySegmentationPrediction
  license: MIT
  license_file: "LICENSE.txt"
  summary: A tool for segmentation and classification
  license_family: MIT
